#! /bin/bash
# APACHE 2.4 & PHP 7.0 & MYSQL 5.7


. "$root/config/lamp/conf"



print_title "Apache 2.4, PHP 7.0, MySQL 5.7: Installation"




print_start "getting repositories.."
sudo add-apt-repository ppa:ondrej/php -y
sudo apt update -y -qq




print_start "installing.."




# APACHE
sudo apt install apache2 libapache2-mod-fastcgi -y



# PHP
# 7.2
sudo apt install php7.2 php7.2-common libapache2-mod-php7.2 php-mongodb php7.2-cli php7.2-fpm php7.2-dev php7.2-curl php7.2-gd php7.2-intl php7.2-xsl php7.2-json php7.2-sqlite3 php7.2-mysql php-redis php7.2-mbstring php7.2-soap php7.2-xml php7.2-zip php7.2-cgi php7.2-bcmath php7.2-sybase -y

# 7.0
sudo apt install php7.0 php7.0-common libapache2-mod-php7.0 php-mongodb php7.0-cli php7.0-fpm php7.0-dev php7.0-curl php7.0-gd php7.0-intl php7.0-mcrypt php7.0-xsl php7.0-json php7.0-sqlite3 php7.0-mysql php-redis php7.0-mbstring php7.0-soap php7.0-xml php7.0-zip php7.0-cgi php7.0-bcmath php7.0-sybase -y

# 5.6 For Backward Compatibility
sudo apt install php5.6 php5.6-common libapache2-mod-php5.6 php5.6-cli php5.6-cgi php5.6-fpm php5.6-curl php5.6-gd php5.6-imap php5.6-intl php5.6-mysql php5.6-sqlite3 php5.6-json php5.6-bz2 php5.6-mcrypt php5.6-bcmath php5.6-mbstring php5.6-xml php5.6-zip -y


# MYSQL
sudo echo "mysql-server-5.7 mysql-server/root_password password $db_root_pass" | sudo debconf-set-selections
sudo echo "mysql-server-5.7 mysql-server/root_password_again password $db_root_pass" | sudo debconf-set-selections
sudo apt install mysql-server -y



print_start "cleaning up.."
sudo apt autoremove -y -qq
print_end "install finished.."

print_start "Make sure edit all conf files including sites configs"



