#! /bin/bash
print_title "Apache 2.4, PHP 7.0, PHP 5.6, MySQL 5.7: Uninstall"
sudo apt purge apache2 -y
sudo apt purge php7.0 php7.0-common libapache2-mod-php7.0 php-mongodb php7.0-cli php7.0-fpm php7.0-dev php7.0-curl php7.0-gd php7.0-intl php7.0-mcrypt php7.0-xsl php7.0-json php7.0-sqlite3 php7.0-mysql php-redis php7.0-mbstring php7.0-soap php7.0-xml php7.0-zip libapache2-mod-php7.0 php7.0-cgi php7.0-bcmath -y
sudo apt purge php5.6 php5.6-common libapache2-mod-php5.6 php5.6-curl php5.6-gd php5.6-imap php5.6-intl php5.6-mysql php5.6-sqlite3 php5.6-json php5.6-bz2 php5.6-mcrypt php5.6-bcmath php5.6-mbstring php5.6-xml php5.6-zip -y
sudo apt purge mysql-server -y
sudo apt autoremove -y -qq

print_end "Apache 2.4, PHP 7.0, PHP 5.6, MySQL 5.7 removed.."


