#! /bin/bash
. "../config/cron/services"

for service in ${services[@]};do

    if (( $(ps -ef | grep -v grep | grep $service | wc -l) > 0 )); then
        echo "$service is running!!!"

    else
        service $service start
    fi
done
