#! /bin/bash
# from "https://github.com/nodesource/distributions"

print_title "Node6.x & npm: Installation"

print_start "getting repositories.."
sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get update -y -qq

print_start "installing.."
sudo apt-get install nodejs -y
sudo apt-get install build-essential -y

print_start "cleaning up.."
sudo apt-get --purge autoremove -y -qq
print_end "install finished.."


