#! /bin/bash
print_title "FFMPEG: Installation"

print_start "getting git repositories.."
sudo apt-get update -y -qq

print_start "installing.."
sudo apt-get install ffmpeg -y

print_start "cleaning up.."
sudo apt-get --purge autoremove -y -qq
print_end "install finished.."


