#! /bin/bash
# Apache2.4 from "https://launchpad.net/~ondrej/+archive/ubuntu/apache2"
# PHP7.0 from "https://launchpad.net/~ondrej/+archive/ubuntu/php"
# MySql5.7 from "http://repo.mysql.com/apt/ubuntu/"
. "$root/apache2.4_php7.0_mysql5.7/inc/conf"


print_title "Apache 2.4, PHP 7.0, MySQL 5.7: Installation"


print_start "getting repositories.."

# apache
sudo add-apt-repository ppa:ondrej/apache2 -y
# php
sudo add-apt-repository ppa:ondrej/php -y
# mysql
sudo apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 5072E1F5
sudo echo "deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7" | sudo tee -a /etc/apt/sources.list.d/mysql.list

sudo apt-get update -y -qq



print_start "installing.."

# apache
sudo apt-get install apache2 -y

# php
# sudo apt-get install php5.6 php5.6-common libapache2-mod-php5.6 php5.6-cgi php5.6-cli php5.6-fpm php5.6-curl php5.6-gd php5.6-imap php5.6-intl php5.6-mysql php5.6-sqlite3 php5.6-json php5.6-bz2 php5.6-mcrypt php5.6-bcmath php5.6-mbstring php5.6-xml php5.6-zip -y
sudo apt-get install php7.0 php7.0-common libapache2-mod-php7.0 php-mongodb php7.0-cli php7.0-fpm php7.0-dev php7.0-curl php7.0-gd php7.0-intl php7.0-mcrypt php7.0-xsl php7.0-json php7.0-sqlite3 php7.0-mysql php-redis php7.0-mbstring php7.0-soap php7.0-xml php7.0-zip libapache2-mod-php7.0 php7.0-cgi php7.0-bcmath -y

# mysql
sudo sed -i "s/listen =.*/listen = 127.0.0.1:9000/" /etc/php/7.0/fpm/pool.d/www.conf
sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/data-dir select ''"
sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/root-pass password $db_root_pass"
sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/re-root-pass password $db_root_pass"
sudo apt-get install -y mysql-server



print_start "cleaning up.."
sudo apt-get --purge autoremove -y -qq
print_end "install finished.."

print_start "Make sure edit all conf files including sites configs"



