#! /bin/bash
print_title "Apache 2.4, PHP 7.0, MySQL 5.7: Uninstall"
sudo apt-get purge --auto-remove apache2 -y
sudo apt-get purge --auto-remove php7.0 php7.0-common libapache2-mod-php7.0 php-mongodb php7.0-cli php7.0-fpm php7.0-dev php7.0-curl php7.0-gd php7.0-intl php7.0-mcrypt php7.0-xsl php7.0-json php7.0-sqlite3 php7.0-mysql php-redis php7.0-mbstring php7.0-soap php7.0-xml php7.0-zip libapache2-mod-php7.0 php7.0-cgi -y
sudo apt-get purge --auto-remove mysql-server -y

print_end "Apache 2.4, PHP 7.0, MySQL 5.7 removed.."


