#! /bin/bash
# This updates installed repositories and upgrade them all

print_title "Build-in Packages: Installation"

print_start "getting updated packages list.."
sudo apt update -y

print_start "upgrading installed packages.."
sudo apt-get upgrade -y

sudo apt install unzip
cd ~
mkdir bin
echo 'export PATH="$PATH:$HOME/bin"' >> ~/.bashrc

print_start "cleaning up.."
sudo apt-get --purge autoremove -y -qq
print_end "install finished.."