#! /bin/bash

# Database Configuration
# mysql root account can only be access within host itself
db_root_pass='root'

# Set databases:
# databases=(
#   'database_name1'
#   'database_name2'
# )
databases=(
  'bm_table'
  'bm_table_1'
  'sincgo'
  'effypiao'
  'autocoin'
  'trece'
)

# Set database users, these users gets all privileges
# databases=(
#   'database_user1_name,database_user1_password',
#   'database_user2_name,database_user2_password'
# )
db_users=(
  'kmstech,Kmsinc123!'
  'admin,777'
  'wonsong82,Dnjscjf0310'
)
