#! /bin/bash

if [ $command == "site" ]; then

    site=$2
    domain=$3
    docroot=$4

    if [ -n "$site" ]; then
        cp $root/config/lamp/sites/sample/sample.conf $root/config/lamp/sites/$site.conf
    fi

    if [ -n "$domain" ]; then
        search="domain.com"
        replace="$domain"
        sed -i "s/$search/$replace/g" $root/config/lamp/sites/$site.conf
    fi


    if [ -n "$docroot" ]; then
        search="/var/www/namespace/name/www"
        replace="$docroot"
        sed -i "s~$search~$replace~g" $root/config/lamp/sites/$site.conf
    fi




    print_end "Apache site config '$site.conf' generated."

fi


if [ $command == "ssl" ]; then

    domain=$2

    sudo mkdir /etc/ssl/$domain
    cd /etc/ssl/$domain

    sudo openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout $domain.key -out $domain.crt

    sudo ufw allow 443



fi



