#!/usr/bin/env bash

if [ -z $1 ]; then
	php -v
else


command=$1
if [ $command == "start" ];then
	sudo phpenmod xdebug
	sudo service php5.6-fpm restart
	sudo service php7.0-fpm restart
	sudo service php7.2-fpm restart
	sudo service php7.3-fpm restart
	sudo service apache2 restart
	php -v
fi

if [ $command == "stop" ];then
	sudo phpdismod xdebug
        sudo service php5.6-fpm restart
	sudo service php7.0-fpm restart
	sudo service php7.2-fpm restart
	sudo service php7.3-fpm restart
	sudo service apache2 restart
	php -v
fi

fi
