#! /bin/bash
. ".script.sh"

# install & setup all available packages
# install
if [ -z $1 ]; then
  for package in ${packages[@]};do	
	require "$root/apps/$version/$package/install"
	require "$root/apps/$version/$package/setup"
  done
  
  
# install & setup specific package(s)
# install $package_name1 $package_name2 ..
else   
  for package in $@;do
    require "$root/apps/$version/$package/install"
	require "$root/apps/$version/$package/setup"
  done  
fi
