#! /bin/bash
. ".script.sh"

# setup all available packages
# setup
if [ -z $1 ]; then
  for package in ${packages[@]};do	
	require "./apps/$version/$package/setup"
  done
  
  
# setup specific package(s)
# setup $package_name1 $package_name2 ..
else   
  for package in $@;do
    require "./apps/$version/$package/setup"
  done  
fi
