#! /bin/bash
print_title "Composer: Configuration"
echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.bashrc
source ~/.bashrc

cp -f $root/apps/$version/composer/config.json ~/.composer/
print_end "finished"